"""runs, run_steps, run_messages

Revision ID: 0ef50bb08163
Revises: 
Create Date: 2026-09-19 21:40:14.909217

Reviewed by hand after autogenerate (CLAUDE.md §4). Alembic gets vector columns and
generated tsvector columns wrong, and a migration nobody read is a schema nobody owns.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0ef50bb08163'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Reviewed by hand. Three changes from the autogenerated output:
    #  1. server_default on every NOT NULL counter and on tenant_id/attempt/tool_calls.
    #     The Python-side default only fires when SQLAlchemy builds the INSERT, so a
    #     raw insert or a later backfill would otherwise violate NOT NULL.
    #  2. Checked that no separate index on run_steps.run_id / run_messages.run_id is
    #     needed: UNIQUE(run_id, idx) already leads with run_id, so lookups by run are
    #     covered and a second index would only cost write throughput.
    #  3. Confirmed ix_runs_reclaimable is partial on status = 'RUNNING' — it exists
    #     for the crash-recovery scan, which only ever asks about a handful of rows.
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('effort', sa.String(length=8), nullable=False),
    sa.Column('prompt_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('steps_taken', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_steps > 0', name='ck_runs_max_steps_positive'),
    sa.CheckConstraint('token_budget > 0', name='ck_runs_token_budget_positive'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_runs_tenant_idempotency')
    )
    op.create_index('ix_runs_created_at_id', 'runs', ['created_at', 'id'], unique=False)
    op.create_index('ix_runs_reclaimable', 'runs', ['lease_expires_at'], unique=False, postgresql_where="status = 'RUNNING'")
    op.create_index('ix_runs_status', 'runs', ['status'], unique=False)
    op.create_table('run_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('step_idx', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('idx >= 0', name='ck_run_messages_idx_non_negative'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idx', name='uq_run_messages_run_idx')
    )
    op.create_table('run_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=24), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('idx >= 0', name='ck_run_steps_idx_non_negative'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idx', name='uq_run_steps_run_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_steps')
    op.drop_table('run_messages')
    op.drop_index('ix_runs_status', table_name='runs')
    op.drop_index('ix_runs_reclaimable', table_name='runs', postgresql_where="status = 'RUNNING'")
    op.drop_index('ix_runs_created_at_id', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
