"""run retry counter

Revision ID: 97be8fa2e40a
Revises: ea639b02cd72
Create Date: 2026-09-19 22:12:15.216242

Reviewed by hand after autogenerate (CLAUDE.md §4). Alembic gets vector columns and
generated tsvector columns wrong, and a migration nobody read is a schema nobody owns.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '97be8fa2e40a'
down_revision: str | None = 'ea639b02cd72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Reviewed by hand, and the review earned its keep: autogenerate also proposed
    #   op.drop_table('test_side_effect_attempts')
    #   op.drop_table('test_side_effects')
    # Those are scratch tables the kill-9 integration test creates. They exist in the
    # developer's database and not in Base.metadata, so the diff read them as tables to
    # remove. Applied blindly against a database that happened to contain anything not
    # described by our models, this migration would have deleted it.
    #
    # The root cause is fixed in alembic/env.py, which now filters autogenerate to the
    # objects we actually own. This is exactly the case CLAUDE.md §4 has in mind when it
    # says every migration gets reviewed by hand after autogenerate.
    op.add_column(
        "runs", sa.Column("retries_used", sa.Integer(), server_default="0", nullable=False)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'retries_used')
    op.create_table('test_side_effects',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_side_effects_pkey')),
    sa.UniqueConstraint('run_id', 'label', name=op.f('test_side_effects_run_id_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('test_side_effect_attempts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attempt_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_side_effect_attempts_pkey'))
    )
    # ### end Alembic commands ###
