"""tool_invocations ledger

Revision ID: ea639b02cd72
Revises: 0ef50bb08163
Create Date: 2026-09-19 21:48:50.189366

Reviewed by hand after autogenerate (CLAUDE.md §4). Alembic gets vector columns and
generated tsvector columns wrong, and a migration nobody read is a schema nobody owns.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ea639b02cd72'
down_revision: str | None = '0ef50bb08163'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Reviewed by hand. No changes needed: every NOT NULL column either carries a
    # server default (is_error, created_at) or is always supplied by the ledger on
    # insert. UNIQUE(idempotency_key) is the constraint the whole mechanism rests on —
    # it is what makes two workers racing the same tool call produce one insert and
    # one conflict, instead of two executions.
    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_idx', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('effect_class', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('is_error', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_tool_invocations_key')
    )
    op.create_index('ix_tool_invocations_run', 'tool_invocations', ['run_id', 'step_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_invocations_run', table_name='tool_invocations')
    op.drop_table('tool_invocations')
    # ### end Alembic commands ###
